services:
  app:
    image: ghcr.io/gabe565/geoip-cache-proxy
    build: .
    environment:
      GEOIP_REDIS_HOST: valkey
    depends_on:
      valkey:
        condition: service_started
    read_only: true
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    develop:
      watch:
        - action: rebuild
          path: /go.*
        - action: rebuild
          path: ./main.go
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./internal

  valkey:
    image: valkey/valkey:7.2-alpine
    ports:
      - 127.0.0.1:6379:6379
