services:
  app:
    image: ghcr.io/gabe565/geoip-cache-proxy
    build: .
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8081:8081
    develop:
      watch:
        - action: rebuild
          path: /go.*
        - action: rebuild
          path: ./main.go
        - action: rebuild
          path: ./cmd
        - action: rebuild
          path: ./internal
